<?php

namespace AppBundle\Repository;

/**
 * CarMakeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarMakeRepository extends \Doctrine\ORM\EntityRepository
{
}
