<?php

namespace AppBundle\Repository;
use Symfony\Component\HttpFoundation\Request;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{
    public function ByPrice(Request $request){

        $qb = $this->createQueryBuilder('c');
        $qb -> select('c');

        if($request->query->has('order')){
            $order = $request->query->get('order');

            if($order == 'Cheapest'){
                $qb -> orderBy('c.price','ASC');
            }
            elseif ($order == 'Expensive'){
                $qb -> orderBy('c.price','DESC');
            }


        }


        return $qb ->getQuery()->getResult();

    }

    public function Expensive($name){

        $qb = $this->createQueryBuilder('c');
        $qb -> select('c');
        $qb -> where('c.Price=20');
        $qb ->andWhere($qb ->expr()->like('c.comment',':n')); //DEDAM TARP PROCENTU PAGAL CONVENCIJA
        $qb ->setParameter('n','%$name%');

        return $qb ->getQuery()->getResult();

    }
}
