<?php

namespace AppBundle\Repository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{
    public function getActive(){

        $qb = $this->createQueryBuilder('c');
        $qb -> select('c');
        $qb -> where('c.price=20');

        return $qb ->getQuery()->getResult();


    }

    public function findByName($name){

        $qb = $this->createQueryBuilder('c');
        $qb -> select('c');
        $qb -> where('c.Price=20');
        $qb ->andWhere($qb ->expr()->like('c.comment',':n')); //DEDAM TARP PROCENTU PAGAL CONVENCIJA
        $qb ->setParameter('n','%$name%');

        return $qb ->getQuery()->getResult();

    }
}
