fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
